generator:
  class: sfPropelGenerator
  param:
    model_class:           SftTipoOrganismo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SftTipoOrganismo
    plural:                SftTipoOrganismos
    route_prefix:          sft_tipo_organismo
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   none

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Tipos de Organismos
        max_per_page: 10
        display: [ nombre, codigo, descripcion ]
      filter:  ~
      form:    ~
      edit:
        title: Edici√≥n del Tipo de Organismo: %%NOMBRE%%
      new:
        title: Nuevo Tipo de Organismo
