generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_propel_route:     1
    css:                   none

    config:
      list:
        title: Listado de grupos

      edit:
        title: Edici√≥n del Grupo: "%%name%%"

      new:
        title: Nuevo Grupo
